#include <config.h>

#define LIB_BIN			(USR_DIR + "/Game/lib/bin")
#define LIB_BULK		(USR_DIR + "/Game/lib/bulk")
#define LIB_WIZBIN		(USR_DIR + "/Game/lib/wizbin")
#define LIB_VERB		(USR_DIR + "/Game/lib/verb")
#define LIB_TIME		(USR_DIR + "/Game/lib/time")
#define GAME_LIB_USTATE		(USR_DIR + "/Game/lib/ustate")
#define GAME_LIB_OBJECT		(USR_DIR + "/Game/lib/object")

#define ALIASD			(USR_DIR + "/Game/sys/aliasd")
#define BAND			(USR_DIR + "/Game/sys/band")
#define BULKD			(USR_DIR + "/Game/sys/bulkd")
#define BIND			(USR_DIR + "/Game/sys/bind")
#define BULKD			(USR_DIR + "/Game/sys/bulkd")
#define VERBD			(USR_DIR + "/Game/sys/verbd")
#define ACCOUNTD		(USR_DIR + "/Game/sys/accountd")
#define SNOOPD			(USR_DIR + "/Game/sys/snoopd")
#define TIMED			(USR_DIR + "/Game/sys/timed")
#define GAME_INITD		(USR_DIR + "/Game/initd")
#define GAME_HELPD		(USR_DIR + "/Game/sys/helpd")
#define GAME_DRIVER		(USR_DIR + "/Game/sys/driver")
#define GAME_USERD		(USR_DIR + "/Game/sys/userd")
#define GAME_ROOT		(USR_DIR + "/Game/sys/root")
#define GAME_SUBD		(USR_DIR + "/Game/sys/subd")
#define GAME_TESTD		(USR_DIR + "/Game/sys/testd")
