#!/bin/bash

exec 1>&2

cd ..

rm -f state/swap

if [ -f state/snapshot ]
then
	if [ -f state/snapshot.old ]
	then
		echo "--- DGD hotbooting ---"
		exec ../dgd/bin/dgd kotaka.dgd state/snapshot state/snapshot.old
	else
		echo "--- DGD hotbooting ---"
		exec ../dgd/bin/dgd kotaka.dgd state/snapshot
	fi
else
	echo "+++ Hotboot aborted (missing snapshot) +++"
	exit 2
fi
