#!/bin/bash

DGD=./dgd
CONFIG=kotaka.dgd
DUMP=snapshot
SWAP=swap

exec 1>&2

cd ..

rm -f state/$SWAP

if [ -f state/$DUMP ]
then
	if [ -f state/$DUMP.old ]
	then
		echo "--- DGD hotbooting ---"
		exec $DGD $CONFIG state/$DUMP state/$DUMP.old
	else
		echo "--- DGD hotbooting ---"
		exec $DGD $CONFIG state/$DUMP
	fi
else
	echo "+++ Hotboot aborted (missing snapshot) +++"
	exit 2
fi
