#!/bin/bash

# signal handlers

# note: we don't CARE if wait gets interrupted
# all handled signals are fatal for the script

DGD=bin/dgd
CONFIG=kotaka.dgd
SWAP=swap
DUMP=snapshot
ERR=kotaka.err

function sigint
{
	# this probably means we were probably started from the command line
	echo "+++ Monitor received SIGINT, killing DGD +++"
	trap - SIGINT
	kill -KILL $DGDPID # DGD ignores SIGINT
	kill -INT $$
}

function sigterm
{
	echo "+++ Monitor received SIGTERM, exiting +++"
	exit
}

function sighup
{
	echo "+++ Monitor received SIGHUP, exiting +++"
	exit
}

function execdgd
{
	trap - SIGHUP
	trap - SIGINT
	exec $DGD $*
}

function boot
{
	rm -f state/$SWAP

	if [ -f state/$DUMP ]
	then
		echo "--- DGD warm booting ---"
		if [ -f state/$DUMP.old ]
		then
			# both are present, possible incremental snapshot
			execdgd $CONFIG state/$DUMP state/$DUMP.old &
		else
			# only the full one
			execdgd $CONFIG state/$DUMP &
		fi
	else
		if [ -f state/$DUMP.old ]
		then
			# we only have the old one
			echo "--- DGD cool booting ---"
			execdgd $CONFIG state/$DUMP.old &
		else
			# complete cold start
			echo "--- DGD cold booting ---"
			execdgd $CONFIG &
		fi
	fi

	DGDPID=$!
}

function exited
{
	case $EXITCODE in
	0)
		echo "--- DGD terminated normally ---"
		;;
	*)
		echo "--- DGD terminated abnormally (code $EXITCODE) ---"
		exit
		;;
	esac
}

function crashed
{
	if [ -f mud/core ]
	then
		rm -rf crash
		mkdir crash
		gdb $DGD mud/core -batch -ex bt > crash/trace
		mv mud/core crash
		echo "+++ DGD terminated by SIG$SIGNAME (core dump processed) +++"
	else
		echo "+++ DGD terminated by SIG$SIGNAME (no core file found) +++"
	fi
}

function signalled
{
	SIGNAME=`kill -l $(( EXITCODE - 128 ))`

	case $SIGNAME in
	KILL|TERM|INT|HUP)
		echo "+++ DGD terminated by SIG$SIGNAME +++"
		exit
		;;
	*)
		crashed
		exit
		;;
	esac
}

function doexit
{
	if (( EXITCODE < 128 ))
	then
		exited
	else
		signalled
	fi
}

exec < /dev/null
exec >> $ERR
exec 2>&1

trap sigint SIGINT
trap sigterm SIGTERM
trap sighup SIGHUP

echo "--- Monitor starting ---"

while true
do
	boot
	wait $DGDPID
	EXITCODE=$?
	doexit
	exec >> $ERR
	exec 2>&1
done
