#!/bin/bash

function crash
{
	echo $*
	exit 1
}

function reb
{
	echo "Rebasing branch \"$1\" onto branch \"$2\"..."

	git checkout $1
	git rebase $2 --interactive || crash "Rebase failed"
}

echo "Rebasing kotaka repository..."

cd ~/git/kotaka

CURRENT=`git status | head -n 1 | cut -d" " -f3`

git stash

reb local master
reb test local
reb siteban test

git checkout $CURRENT
git stash pop
