#!/bin/bash

#TMPDIR=`mktemp -d`

find mudlib -type f -name "*.[ch]" > checklist

rm -f fixme

(
IFS=$'\n'
for file in `cat checklist`
do
	git log $file | egrep "^Date:" | tr -s " " | cut -d " " -f 6 | sort | uniq > dates
	echo $file
	cat dates
done
)

#rm -rf $TMPDIR
