#!/bin/bash

find mudlib -type f -name "*.[ch]" | sort > checklist

YEARS="2000 2001 2002 2003 2004 2005 2006 2007 2008 2009 2010 2011 2012 2013 2014"

ERRORS=0
(
IFS=$'\n'
for file in `cat checklist`
do
	git log --follow $file > gityears
	head -15 $file | egrep "^ \* Copyright" - > headyears

	IFS=$' \n'
	for year in $YEARS
	do
		if grep $year gityears > /dev/null
		then
			if grep $year headyears > /dev/null
			then
				true
			else
				echo "$file is missing $year"
				ERRORS=$(($ERRORS + 1))
			fi
		else
			if grep $year headyears > /dev/null
			then
				echo "$file has unneeded $year"
				ERRORS=$(($ERRORS + 1))
			else
				true
			fi
		fi
	done
done
)
