#!/bin/bash

cd ~/dgd/ulario

DGDPID=0

function sigterm
{
	kill -TERM $DGDPID
	kill -KILL $MONPID
	trap - SIGTERM
	kill -TERM $$
}

function sigint
{
	kill -KILL $DGDPID
	kill -KILL $MONPID
	trap - SIGINT
	kill -INT $$
}

function crashed
{
	echo "Found a core dump!"

	rm -rf crash
	mkdir crash

	gdb dgd mud/core -batch -ex bt > crash/trace
	mv mud/core crash
}

trap sigterm SIGTERM
trap sigint SIGINT

rm -f mud/core
rm -f namedump

while true
do
	if [ -f ulario.snapshot ]
	then
		echo "Warm booting dgd" >> ulario.err
		~/bin/dgd ulario.dgd ulario.snapshot < /dev/null >> ulario.err 2>&1 &
	else
		echo "Cold booting dgd" >> ulario.err
		~/bin/dgd ulario.dgd < /dev/null >> ulario.err 2>&1 &
	fi

	DGDPID=$!
	wait

	echo "dgd ended" >> ulario.err

	[ -f mud/core ] && crashed
done
