#!/bin/bash

find mudlib -type f -name "*.[ch]" | sort > checklist

YEARS="2000 2001 2002 2003 2004 2005 2006 2007 2008 2009 2010 2011 2012 2013 2014"

ERRORS=0
(
IFS=$'\n'
for file in `cat checklist`
do
	echo "Checking $file"
	git log --follow $file > gityears
	head -15 $file | egrep "^ \* Copyright" - > headyears

	COPYRIGHT=""

	IFS=$' \n'
	for year in $YEARS
	do
		if grep $year gityears > /dev/null
		then
			COPYRIGHT="$COPYRIGHT, $year"
		fi
	done

	COPYRIGHT=`echo $COPYRIGHT | sed -e "s_^, __"`

	sed -i -e "s_^ \* Copyright.*_ \* Copyright (C) $COPYRIGHT  Raymond Jennings_" $file
done
)
