#!/bin/bash

MUDNAME=ulario

# purge

echo "Purging old layout..."

cd ~
rm -rf dgd/$MUDNAME/mud/*
rm -rf dgd/$MUDNAME/tmp

# skeleton

echo "Building directory skeleton..."

mkdir -p dgd
mkdir -p dgd/$MUDNAME
mkdir -p dgd/$MUDNAME/mud
mkdir -p dgd/$MUDNAME/mud/doc
mkdir -p dgd/$MUDNAME/mud/doc/kernel
mkdir -p dgd/$MUDNAME/mud/doc/kfun
mkdir -p dgd/$MUDNAME/mud/home
mkdir -p dgd/$MUDNAME/mud/include
mkdir -p dgd/$MUDNAME/mud/kernel
mkdir -p dgd/$MUDNAME/mud/kernel/data
mkdir -p dgd/$MUDNAME/mud/log
mkdir -p dgd/$MUDNAME/tmp

# dgd

echo "Setting up dgd links..."

for d in net builtin
do
	ln -s ../../../../git/dgd/doc/$d dgd/$MUDNAME/mud/doc
done

echo "Setting up lpc-doc links..."

for d in editor ed-quickref Introduction parser
do
	ln -s ../../../../git/lpc-doc/$d dgd/$MUDNAME/mud/doc
done

echo "Copying kfun documents..."

# defaults are in lpc-doc
for d in git/lpc-doc/kfun/*
do
	cp -r $d dgd/$MUDNAME/mud/doc/kfun
done

# overwrite with any dgd specific docs
for d in git/dgd/doc/kfun/*
do
	cp -r $d dgd/$MUDNAME/mud/doc/kfun
done

# kernel-lib

echo "Setting up kernel library symlinks..."

for d in efun hook lfun
do
	ln -s ../../../../../git/kernellib/doc/kernel/$d dgd/$MUDNAME/mud/doc/kernel
done

for d in lib obj sys
do
	ln -s ../../../../git/kernellib/kernel/$d dgd/$MUDNAME/mud/kernel
done

ln -s ../../../../git/kernellib/include/kernel dgd/$MUDNAME/mud/include

# kotaka

echo "Setting up kotaka symlinks..."

for d in git/kotaka/mudlib/mud/home/*
do
	ln -s ../../../../$d dgd/$MUDNAME/mud/home
done

for d in git/kotaka/mudlib/mud/include/*
do
	ln -s ../../../../$d dgd/$MUDNAME/mud/include
done

for d in git/kotaka/mudlib/mud/doc/*
do
	ln -s ../../../../$d dgd/$MUDNAME/mud/doc
done

echo "Copying configuration file..."

cp git/kotaka/mudlib/kotaka.dgd dgd/$MUDNAME/$MUDNAME.dgd

echo "Completed."
