#!/bin/bash

# purge

echo "Purging old layout..."

cd ~
rm -rf dgd/kotaka/mud/*
rm -rf dgd/kotaka/tmp

# skeleton

echo "Building directory skeleton..."

mkdir -p dgd
mkdir -p dgd/kotaka
mkdir -p dgd/kotaka/mud
mkdir -p dgd/kotaka/mud/doc
mkdir -p dgd/kotaka/mud/doc/kernel
mkdir -p dgd/kotaka/mud/home
mkdir -p dgd/kotaka/mud/include
mkdir -p dgd/kotaka/mud/kernel
mkdir -p dgd/kotaka/mud/kernel/data
mkdir -p dgd/kotaka/mud/log
mkdir -p dgd/kotaka/tmp

# dgd

echo "Setting up dgd links..."

for d in kfun net editor parser
do
	ln -s ../../../../git/dgd/doc/$d dgd/kotaka/mud/doc
done

# kernel-lib

echo "Setting up kernel library symlinks..."

for d in efun hook lfun
do
	ln -s ../../../../../git/kernellib/doc/kernel/$d dgd/kotaka/mud/doc/kernel
done

for d in lib obj sys
do
	ln -s ../../../../git/kernellib/kernel/$d dgd/kotaka/mud/kernel
done

ln -s ../../../../git/kernellib/include/kernel dgd/kotaka/mud/include

# kotaka

echo "Setting up kotaka symlinks..."

for d in git/kotaka/mudlib/mud/home/*
do
	ln -s ../../../../$d dgd/kotaka/mud/home
done

for d in git/kotaka/mudlib/mud/include/*
do
	ln -s ../../../../$d dgd/kotaka/mud/include
done

for d in git/kotaka/mudlib/mud/doc/*
do
	ln -s ../../../../$d dgd/kotaka/mud/doc
done

echo "Copying configuration file..."

cp git/kotaka/mudlib/kotaka.dgd dgd/kotaka

echo "Completed."
